Bugfix/some fix
LuizLimaDev/front-back-montain-frontend pull request #165
Opened 2023-10-03 04:09 UTC by Engenuis

Solucionados os problemas solicitados!

2023-10-03 17:16 UTC, LuizLimaDev approved these changes
ok

2023-10-03 17:52 UTC, Fernanda-Campelo approved these changes
Ok.

2023-10-03 18:02 UTC, Amandalfs requested changes

2023-10-03 18:02 UTC, Amandalfs commented on src/components/Utils/Modals/EditClient/index.jsx
essa rota serve somente para validar email de usuario e nao de clientes

2023-10-04 18:22 UTC, Amandalfs approved these changes

2023-10-04 18:23 UTC, merged