consertar valores altos quebrando a tabela
LuizLimaDev/front-back-montain-frontend pull request #175
Opened 2023-10-03 19:10 UTC by Fernanda-Campelo

# Descrição
Arrumar bug dos valores altos quebrando as tabelas de cobranças

Corrige # (issue)
#163

## Tipo de Alteração
- [x] Correção de bug (alteração que não quebra e resolve um problema)

# Checklist:
- [x] Meu código segue as diretrizes de estilo deste projeto
- [x] Eu revisei meu próprio código

2023-10-03 19:32 UTC, Amandalfs approved these changes

2023-10-04 12:07 UTC, LuizLimaDev commented
Tem conflitos para resolver antes do Merge.

2023-10-04 13:59 UTC, Fernanda-Campelo commented
Conflitos resolvidos

2023-10-04 14:04 UTC, Amandalfs requested changes

2023-10-04 14:04 UTC, Amandalfs commented on src/components/DataDisplay/Tables/Billing-detailed/billing-detailed-projected/index.jsx
faltou uma chave no componente

2023-10-04 18:27 UTC, Amandalfs approved these changes

2023-10-04 18:28 UTC, Edualct approved these changes
ok

2023-10-04 18:29 UTC, merged